# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the jar file from the host machine to the container
COPY target/order-service.jar /app/order-service.jar

# Expose the port your application will run on
EXPOSE 8080

# Run the JAR file when the container starts
CMD ["java", "-jar", "order-service.jar"]
